name: Deploy Portfolio on push to main
on:
  push:
    branches: [main]
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      # Now Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: npm install @salesforce/cli --global
        
      - name: 'Installing sfdx git delta'
        run: |
            echo Y | sfdx plugins:install sfdx-git-delta
            sfdx plugins
        
      - name: 'Create delta packages'
        run: |
            mkdir changed-sources
            sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta 
            --source force-app/
            echo "[INFO] Diff generated successfully"

      - name: 'Deploy to environment with running all local tests'
        run: |
           echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
           sf org login jwt --username ${{ secrets.DEPLOYMENT_USERNAME }} -- jwt-key-file server.key
           --clientid ${{ secrets.JWT_CLIENT_ID }} --instanceurl ${{ vars.INSTANCE_URL }}
           --set-default
           sf project deploy start --source-path changed-sources/force-app --test-level RunLocalTests --wait 10

